name: your_app_name  # Change this to your app's name
description: A new Flutter project.

publish_to: 'none'  # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Adjust according to your Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3  # For making HTTP requests
  cupertino_icons: ^1.0.8  # For iOS style icons
  image_picker: ^1.1.2  # For picking images from the gallery or camera

dev_dependencies:
  flutter_lints: ^2.0.0  # Use the latest version for linting

flutter:
  uses-material-design: true  # Enable Material Design
  assets:
    - assets/flutter-navigator.png  # Make sure this path is correct
