name: your_app_name  # Replace with your app's name
description: A new Flutter project.

publish_to: 'none'  # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Ensure Dart SDK version matches your current SDK
  
dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  http: ^0.13.6  # This was already fixed in the previous step
  cupertino_icons: ^1.0.8  # Downgrade this to 1.0.8 or use the latest compatible version
  image_picker: ^0.8.6


dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
